import { canonicalScienceSources } from "./scienceSources";
import { parseWeatherScenario, type WeatherScenarioV1 } from "./schema";

const coreSources = canonicalScienceSources;

const commonLearningObjectives = [
  "Use temperature, pressure, moisture, wind, and precipitation evidence to reason about changing weather.",
  "Connect air-mass and boundary movement to changes at fixed observing stations.",
  "Make a forecast within a defensible range and calibrate confidence to the evidence.",
];

const commonSimplifications = [
  {
    id: "fictional-region",
    description:
      "The region and observing stations are synthetic; coordinates are normalized and do not represent a live location.",
    learnerFacing: true,
  },
  {
    id: "pedagogical-dynamics",
    description:
      "Front motion and station changes are authored causal rules, not a numerical fluid-dynamics forecast model.",
    learnerFacing: true,
  },
  {
    id: "bounded-precipitation",
    description:
      "Precipitation fields are simplified evidence bands and do not simulate cloud microphysics or convection.",
    learnerFacing: true,
  },
  {
    id: "schematic-front-geometry",
    description:
      "Fronts are drawn as straight boundaries translating across a simplified region; real fronts curve, connect to low-pressure centers, and travel in other directions.",
    learnerFacing: true,
  },
] as const;

const guidedColdFront = parseWeatherScenario({
  schemaVersion: "1",
  contentVersion: "wc04-guided-cold-front-2",
  scenarioId: "guided-cold-front-shift",
  title: "Cold Front Shift",
  missionType: "guided-cold-front",
  objective:
    "Forecast when the main weather change will reach Central Station and explain the evidence supporting that forecast.",
  learningObjectives: commonLearningObjectives,
  seed: 2026092101,
  scienceReviewStatus: "pending-independent",
  timeline: {
    startMinute: 0,
    stepMinutes: 30,
    maxMinute: 240,
    checkpoints: [0, 60, 120, 180, 240],
  },
  stations: [
    {
      id: "west",
      name: "West Station",
      position: { x: 0.22, y: 0.52 },
      initial: {
        temperatureC: 22,
        pressureHpa: 1007,
        pressureTendencyHpaPer3h: -2,
        relativeHumidityPct: 76,
        windDirectionDeg: 185,
        windSpeedMps: 4,
        precipitationRateMmh: 0,
      },
    },
    {
      id: "central",
      name: "Central Station",
      position: { x: 0.5, y: 0.5 },
      initial: {
        temperatureC: 23,
        pressureHpa: 1006,
        pressureTendencyHpaPer3h: -2,
        relativeHumidityPct: 78,
        windDirectionDeg: 190,
        windSpeedMps: 4,
        precipitationRateMmh: 0,
      },
    },
    {
      id: "east",
      name: "East Station",
      position: { x: 0.78, y: 0.48 },
      initial: {
        temperatureC: 24,
        pressureHpa: 1005,
        pressureTendencyHpaPer3h: -2,
        relativeHumidityPct: 80,
        windDirectionDeg: 195,
        windSpeedMps: 5,
        precipitationRateMmh: 0,
      },
    },
  ],
  airMasses: [
    {
      id: "cool-dry",
      label: "Cooler, drier air",
      initialCenter: { x: 0.02, y: 0.5 },
      movement: { x: 0.12, y: 0 },
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
    {
      id: "warm-moist",
      label: "Warmer, moister air",
      initialCenter: { x: 0.72, y: 0.5 },
      movement: { x: 0.02, y: 0 },
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
  ],
  boundaries: [
    {
      id: "cold-front",
      kind: "cold-front",
      airMassAId: "cool-dry",
      airMassBId: "warm-moist",
      initialPath: [
        { x: 0.09, y: 0.08 },
        { x: 0.09, y: 0.92 },
      ],
      movement: { x: 0.12, y: 0 },
      transitionWidth: 0.12,
      sourceRefIds: ["nws-fronts", "noaa-weather-map"],
    },
  ],
  precipitationCells: [
    {
      id: "frontal-band",
      initialCenter: { x: 0.09, y: 0.5 },
      movement: { x: 0.12, y: 0 },
      initialIntensityMmh: 4,
      intensityDeltaMmhPerStep: -0.1,
      sourceRefIds: ["nws-fronts"],
    },
  ],
  stationEffects: [
    {
      id: "west-passage",
      stationId: "west",
      boundaryId: "cold-front",
      startMinute: 30,
      endMinute: 60,
      delta: {
        temperatureC: -7,
        pressureHpa: 4,
        pressureTendencyHpaPer3h: 4,
        relativeHumidityPct: -18,
        windDirectionDeg: 75,
        windSpeedMps: 3,
        precipitationRateMmh: 4,
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "west-clearing",
      stationId: "west",
      boundaryId: "cold-front",
      startMinute: 90,
      endMinute: 150,
      delta: { relativeHumidityPct: -8, precipitationRateMmh: -4 },
      sourceRefIds: ["nws-fronts"],
    },
    {
      id: "central-passage",
      stationId: "central",
      boundaryId: "cold-front",
      startMinute: 90,
      endMinute: 120,
      delta: {
        temperatureC: -7,
        pressureHpa: 4,
        pressureTendencyHpaPer3h: 4,
        relativeHumidityPct: -18,
        windDirectionDeg: 75,
        windSpeedMps: 3,
        precipitationRateMmh: 4,
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "central-clearing",
      stationId: "central",
      boundaryId: "cold-front",
      startMinute: 150,
      endMinute: 210,
      delta: { relativeHumidityPct: -8, precipitationRateMmh: -4 },
      sourceRefIds: ["nws-fronts"],
    },
    {
      id: "east-passage",
      stationId: "east",
      boundaryId: "cold-front",
      startMinute: 150,
      endMinute: 180,
      delta: {
        temperatureC: -7,
        pressureHpa: 4,
        pressureTendencyHpaPer3h: 4,
        relativeHumidityPct: -18,
        windDirectionDeg: 75,
        windSpeedMps: 3,
        precipitationRateMmh: 4,
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "east-clearing",
      stationId: "east",
      boundaryId: "cold-front",
      startMinute: 210,
      endMinute: 240,
      delta: { relativeHumidityPct: -8, precipitationRateMmh: -4 },
      sourceRefIds: ["nws-fronts"],
    },
  ],
  forecastWindows: [
    {
      id: "central-next-three-hours",
      targetStationIds: ["central"],
      startMinute: 0,
      endMinute: 150,
    },
  ],
  evidence: [
    {
      id: "guided-stations-initial",
      type: "station",
      availableAtMinute: 0,
      targetIds: ["west", "central", "east"],
      learningTags: ["compare-locations", "baseline"],
    },
    {
      id: "guided-pressure-trend",
      type: "trend",
      availableAtMinute: 30,
      targetIds: ["west", "central", "east"],
      learningTags: ["pressure", "timing"],
    },
    {
      id: "guided-front-position",
      type: "boundary",
      availableAtMinute: 30,
      targetIds: ["cold-front"],
      learningTags: ["front-motion", "timing"],
    },
    {
      id: "guided-precipitation-band",
      type: "precipitation",
      availableAtMinute: 60,
      targetIds: ["frontal-band"],
      learningTags: ["precipitation", "front-motion"],
    },
  ],
  acceptedRanges: [
    {
      id: "guided-central-forecast",
      forecastWindowId: "central-next-three-hours",
      targetStationId: "central",
      transitionArrivalMinute: { min: 90, max: 120 },
      temperatureChangeC: { min: -8, max: -5 },
      precipitationProbabilityPct: { min: 60, max: 90 },
      windDirectionSectorsDeg: [{ min: 240, max: 300 }],
      defensibleConfidence: ["medium", "high"],
    },
  ],
  debrief: [
    {
      id: "guided-central-change",
      evidenceIds: [
        "guided-pressure-trend",
        "guided-front-position",
        "guided-precipitation-band",
      ],
      outcomeDimensions: ["temperature", "pressure", "wind", "precipitation", "timing"],
      explanation:
        "The advancing cold boundary reached Central Station after the earlier western change. The authored outcome pairs a temperature drop and wind shift with a pressure-tendency reversal and a temporary precipitation band.",
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
  ],
  sources: coreSources,
  simplifications: commonSimplifications,
});

const independentColdFront = parseWeatherScenario({
  schemaVersion: "1",
  contentVersion: "wc04-independent-cold-front-2",
  scenarioId: "independent-cold-front-variant",
  title: "Front Timing Challenge",
  missionType: "independent-cold-front",
  objective:
    "Use the station sequence and boundary motion to forecast Central Station without tutorial callouts.",
  learningObjectives: commonLearningObjectives,
  seed: 2026092102,
  scienceReviewStatus: "pending-independent",
  timeline: {
    startMinute: 0,
    stepMinutes: 30,
    maxMinute: 300,
    checkpoints: [0, 60, 120, 180, 240, 300],
  },
  stations: [
    {
      id: "west",
      name: "Pine Station",
      position: { x: 0.32, y: 0.45 },
      initial: {
        temperatureC: 20,
        pressureHpa: 1009,
        pressureTendencyHpaPer3h: -1.5,
        relativeHumidityPct: 66,
        windDirectionDeg: 175,
        windSpeedMps: 5,
        precipitationRateMmh: 0,
      },
    },
    {
      id: "central",
      name: "Lake Station",
      position: { x: 0.52, y: 0.54 },
      initial: {
        temperatureC: 22,
        pressureHpa: 1008,
        pressureTendencyHpaPer3h: -1.5,
        relativeHumidityPct: 69,
        windDirectionDeg: 185,
        windSpeedMps: 5,
        precipitationRateMmh: 0,
      },
    },
    {
      id: "east",
      name: "Ridge Station",
      position: { x: 0.72, y: 0.48 },
      initial: {
        temperatureC: 23,
        pressureHpa: 1007,
        pressureTendencyHpaPer3h: -1.5,
        relativeHumidityPct: 72,
        windDirectionDeg: 190,
        windSpeedMps: 6,
        precipitationRateMmh: 0,
      },
    },
  ],
  airMasses: [
    {
      id: "cooler-dry-air",
      label: "Cooler, drier air",
      initialCenter: { x: 0.02, y: 0.5 },
      movement: { x: 0.1, y: 0 },
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
    {
      id: "mild-moist-air",
      label: "Mild, moister air",
      initialCenter: { x: 0.68, y: 0.5 },
      movement: { x: 0.015, y: 0 },
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
  ],
  boundaries: [
    {
      id: "cold-front",
      kind: "cold-front",
      airMassAId: "cooler-dry-air",
      airMassBId: "mild-moist-air",
      initialPath: [
        { x: 0.08, y: 0.08 },
        { x: 0.08, y: 0.92 },
      ],
      movement: { x: 0.1, y: 0 },
      transitionWidth: 0.1,
      sourceRefIds: ["nws-fronts", "noaa-weather-map"],
    },
  ],
  precipitationCells: [
    {
      id: "broken-frontal-showers",
      initialCenter: { x: 0.08, y: 0.5 },
      movement: { x: 0.1, y: 0 },
      initialIntensityMmh: 2.5,
      intensityDeltaMmhPerStep: -0.08,
      sourceRefIds: ["nws-fronts"],
    },
  ],
  stationEffects: [
    {
      id: "west-change",
      stationId: "west",
      boundaryId: "cold-front",
      startMinute: 60,
      endMinute: 90,
      delta: {
        temperatureC: -6,
        pressureHpa: 4,
        pressureTendencyHpaPer3h: 3,
        relativeHumidityPct: -14,
        windDirectionDeg: 85,
        windSpeedMps: 2.5,
        precipitationRateMmh: 2,
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "central-change",
      stationId: "central",
      boundaryId: "cold-front",
      startMinute: 120,
      endMinute: 150,
      delta: {
        temperatureC: -6,
        pressureHpa: 4,
        pressureTendencyHpaPer3h: 3,
        relativeHumidityPct: -14,
        windDirectionDeg: 85,
        windSpeedMps: 2.5,
        precipitationRateMmh: 2,
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "east-change",
      stationId: "east",
      boundaryId: "cold-front",
      startMinute: 180,
      endMinute: 210,
      delta: {
        temperatureC: -6,
        pressureHpa: 4,
        pressureTendencyHpaPer3h: 3,
        relativeHumidityPct: -14,
        windDirectionDeg: 85,
        windSpeedMps: 2.5,
        precipitationRateMmh: 2,
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "west-drying",
      stationId: "west",
      boundaryId: "cold-front",
      startMinute: 120,
      endMinute: 180,
      delta: { relativeHumidityPct: -6, precipitationRateMmh: -2 },
      sourceRefIds: ["nws-fronts"],
    },
    {
      id: "central-drying",
      stationId: "central",
      boundaryId: "cold-front",
      startMinute: 180,
      endMinute: 240,
      delta: { relativeHumidityPct: -6, precipitationRateMmh: -2 },
      sourceRefIds: ["nws-fronts"],
    },
    {
      id: "east-drying",
      stationId: "east",
      boundaryId: "cold-front",
      startMinute: 240,
      endMinute: 300,
      delta: { relativeHumidityPct: -6, precipitationRateMmh: -2 },
      sourceRefIds: ["nws-fronts"],
    },
  ],
  forecastWindows: [
    {
      id: "lake-next-four-hours",
      targetStationIds: ["central"],
      startMinute: 30,
      endMinute: 180,
    },
  ],
  evidence: [
    {
      id: "independent-station-sequence",
      type: "trend",
      availableAtMinute: 60,
      targetIds: ["west", "central", "east"],
      learningTags: ["sequence", "timing", "pressure"],
    },
    {
      id: "independent-front-motion",
      type: "boundary",
      availableAtMinute: 60,
      targetIds: ["cold-front"],
      learningTags: ["front-motion", "timing"],
    },
    {
      id: "independent-showers",
      type: "precipitation",
      availableAtMinute: 90,
      targetIds: ["broken-frontal-showers"],
      learningTags: ["precipitation", "uncertainty"],
    },
  ],
  acceptedRanges: [
    {
      id: "independent-central-forecast",
      forecastWindowId: "lake-next-four-hours",
      targetStationId: "central",
      transitionArrivalMinute: { min: 120, max: 150 },
      temperatureChangeC: { min: -8, max: -4 },
      precipitationProbabilityPct: { min: 45, max: 75 },
      windDirectionSectorsDeg: [{ min: 240, max: 300 }],
      defensibleConfidence: ["medium", "high"],
    },
  ],
  debrief: [
    {
      id: "independent-sequence-debrief",
      evidenceIds: ["independent-station-sequence", "independent-front-motion"],
      outcomeDimensions: ["temperature", "pressure", "wind", "timing"],
      explanation:
        "The western station changed first, followed by Central and then the eastern station. That ordered pattern, together with boundary motion, supports the arrival-time forecast without requiring a memorized map symbol.",
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
    {
      id: "independent-precip-debrief",
      evidenceIds: ["independent-showers"],
      outcomeDimensions: ["precipitation", "uncertainty"],
      explanation:
        "The scenario uses a weaker broken shower band so precipitation confidence should be lower than confidence in the main temperature and wind shift.",
      sourceRefIds: ["nws-fronts"],
    },
  ],
  sources: coreSources,
  simplifications: commonSimplifications,
});

const warmFront = parseWeatherScenario({
  schemaVersion: "1",
  contentVersion: "wc04-warm-front-2",
  scenarioId: "warm-front-gradual-change",
  title: "Gradual Change",
  missionType: "warm-front",
  objective:
    "Distinguish a gradual warm-front pattern from the sharper cold-front missions and forecast the Central Station transition.",
  learningObjectives: commonLearningObjectives,
  seed: 2026092103,
  scienceReviewStatus: "pending-independent",
  timeline: {
    startMinute: 0,
    stepMinutes: 30,
    maxMinute: 300,
    checkpoints: [0, 60, 120, 180, 240, 300],
  },
  stations: [
    {
      id: "west",
      name: "Meadow Station",
      position: { x: 0.26, y: 0.52 },
      initial: {
        temperatureC: 16,
        pressureHpa: 1015,
        pressureTendencyHpaPer3h: -1,
        relativeHumidityPct: 65,
        windDirectionDeg: 105,
        windSpeedMps: 3,
        precipitationRateMmh: 0,
      },
    },
    {
      id: "central",
      name: "Valley Station",
      position: { x: 0.53, y: 0.5 },
      initial: {
        temperatureC: 15,
        pressureHpa: 1016,
        pressureTendencyHpaPer3h: -1,
        relativeHumidityPct: 62,
        windDirectionDeg: 110,
        windSpeedMps: 3,
        precipitationRateMmh: 0,
      },
    },
    {
      id: "east",
      name: "Grove Station",
      position: { x: 0.8, y: 0.48 },
      initial: {
        temperatureC: 14,
        pressureHpa: 1017,
        pressureTendencyHpaPer3h: -1,
        relativeHumidityPct: 60,
        windDirectionDeg: 115,
        windSpeedMps: 3,
        precipitationRateMmh: 0,
      },
    },
  ],
  airMasses: [
    {
      id: "warm-moist",
      label: "Warmer, moister air",
      initialCenter: { x: 0.01, y: 0.5 },
      movement: { x: 0.1, y: 0 },
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
    {
      id: "cool-air",
      label: "Cooler air",
      initialCenter: { x: 0.74, y: 0.5 },
      movement: { x: 0.01, y: 0 },
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
  ],
  boundaries: [
    {
      id: "warm-front",
      kind: "warm-front",
      airMassAId: "warm-moist",
      airMassBId: "cool-air",
      initialPath: [
        { x: 0.06, y: 0.08 },
        { x: 0.06, y: 0.92 },
      ],
      movement: { x: 0.1, y: 0 },
      transitionWidth: 0.3,
      sourceRefIds: ["nws-fronts", "noaa-weather-map"],
    },
  ],
  precipitationCells: [
    {
      id: "broad-light-rain",
      initialCenter: { x: 0.14, y: 0.5 },
      movement: { x: 0.1, y: 0 },
      initialIntensityMmh: 2.2,
      intensityDeltaMmhPerStep: -0.05,
      sourceRefIds: ["nws-fronts"],
    },
  ],
  stationEffects: [
    {
      id: "west-gradual-change",
      stationId: "west",
      boundaryId: "warm-front",
      startMinute: 30,
      endMinute: 120,
      delta: {
        temperatureC: 5,
        pressureHpa: -2,
        pressureTendencyHpaPer3h: 1.5,
        relativeHumidityPct: 12,
        windDirectionDeg: 50,
        windSpeedMps: 2,
        precipitationRateMmh: 2,
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "central-gradual-change",
      stationId: "central",
      boundaryId: "warm-front",
      startMinute: 90,
      endMinute: 180,
      delta: {
        temperatureC: 5,
        pressureHpa: -2,
        pressureTendencyHpaPer3h: 1.5,
        relativeHumidityPct: 12,
        windDirectionDeg: 50,
        windSpeedMps: 2,
        precipitationRateMmh: 2,
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "east-gradual-change",
      stationId: "east",
      boundaryId: "warm-front",
      startMinute: 150,
      endMinute: 240,
      delta: {
        temperatureC: 5,
        pressureHpa: -2,
        pressureTendencyHpaPer3h: 1.5,
        relativeHumidityPct: 12,
        windDirectionDeg: 50,
        windSpeedMps: 2,
        precipitationRateMmh: 2,
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "west-rain-eases",
      stationId: "west",
      boundaryId: "warm-front",
      startMinute: 180,
      endMinute: 240,
      delta: { precipitationRateMmh: -2 },
      sourceRefIds: ["nws-fronts"],
    },
    {
      id: "central-rain-eases",
      stationId: "central",
      boundaryId: "warm-front",
      startMinute: 240,
      endMinute: 300,
      delta: { precipitationRateMmh: -2 },
      sourceRefIds: ["nws-fronts"],
    },
  ],
  forecastWindows: [
    {
      id: "valley-next-four-hours",
      targetStationIds: ["central"],
      startMinute: 30,
      endMinute: 210,
    },
  ],
  evidence: [
    {
      id: "warm-gradual-trends",
      type: "trend",
      availableAtMinute: 60,
      targetIds: ["west", "central", "east"],
      learningTags: ["gradual-change", "temperature", "pressure"],
    },
    {
      id: "warm-boundary",
      type: "boundary",
      availableAtMinute: 60,
      targetIds: ["warm-front"],
      learningTags: ["front-motion", "timing"],
    },
    {
      id: "warm-broad-rain",
      type: "precipitation",
      availableAtMinute: 90,
      targetIds: ["broad-light-rain"],
      learningTags: ["precipitation", "gradual-change"],
    },
  ],
  acceptedRanges: [
    {
      id: "warm-central-forecast",
      forecastWindowId: "valley-next-four-hours",
      targetStationId: "central",
      transitionArrivalMinute: { min: 120, max: 180 },
      temperatureChangeC: { min: 3, max: 7 },
      precipitationProbabilityPct: { min: 60, max: 85 },
      windDirectionSectorsDeg: [{ min: 130, max: 190 }],
      defensibleConfidence: ["medium"],
    },
  ],
  debrief: [
    {
      id: "warm-gradual-debrief",
      evidenceIds: ["warm-gradual-trends", "warm-boundary", "warm-broad-rain"],
      outcomeDimensions: ["temperature", "pressure", "moisture", "wind", "precipitation", "timing"],
      explanation:
        "The warm-front scenario changes Central Station over several steps rather than one abrupt passage. The broader light-rain signal and slower temperature/wind transition distinguish it from the cold-front missions.",
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
  ],
  sources: coreSources,
  simplifications: commonSimplifications,
});

const uncertainBoundary = parseWeatherScenario({
  schemaVersion: "1",
  contentVersion: "wc04-uncertain-boundary-2",
  scenarioId: "uncertain-boundary-variant",
  title: "Uncertain Timing",
  missionType: "uncertain-boundary",
  objective:
    "Make a defensible forecast when the direction of change is visible but exact timing and precipitation are less certain.",
  learningObjectives: commonLearningObjectives,
  seed: 2026092104,
  scienceReviewStatus: "pending-independent",
  timeline: {
    startMinute: 0,
    stepMinutes: 30,
    maxMinute: 300,
    checkpoints: [0, 60, 120, 180, 240, 300],
  },
  stations: [
    {
      id: "west",
      name: "Cedar Station",
      position: { x: 0.38, y: 0.45 },
      initial: {
        temperatureC: 20,
        pressureHpa: 1010,
        pressureTendencyHpaPer3h: -0.8,
        relativeHumidityPct: 70,
        windDirectionDeg: 165,
        windSpeedMps: 4,
        precipitationRateMmh: 0,
      },
    },
    {
      id: "central",
      name: "Harbor Station",
      position: { x: 0.56, y: 0.53 },
      initial: {
        temperatureC: 21,
        pressureHpa: 1009,
        pressureTendencyHpaPer3h: -0.8,
        relativeHumidityPct: 72,
        windDirectionDeg: 170,
        windSpeedMps: 4.5,
        precipitationRateMmh: 0,
      },
    },
    {
      id: "east",
      name: "Field Station",
      position: { x: 0.74, y: 0.48 },
      initial: {
        temperatureC: 22,
        pressureHpa: 1008,
        pressureTendencyHpaPer3h: -0.8,
        relativeHumidityPct: 74,
        windDirectionDeg: 175,
        windSpeedMps: 5,
        precipitationRateMmh: 0,
      },
    },
  ],
  airMasses: [
    {
      id: "cooler-air",
      label: "Cooler air",
      initialCenter: { x: 0.01, y: 0.5 },
      movement: { x: 0.1, y: 0 },
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
    {
      id: "milder-air",
      label: "Milder, moister air",
      initialCenter: { x: 0.68, y: 0.5 },
      movement: { x: 0.015, y: 0 },
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
  ],
  boundaries: [
    {
      id: "uncertain-cold-boundary",
      kind: "cold-front",
      airMassAId: "cooler-air",
      airMassBId: "milder-air",
      initialPath: [
        { x: 0.06, y: 0.08 },
        { x: 0.06, y: 0.92 },
      ],
      movement: { x: 0.1, y: 0 },
      transitionWidth: 0.2,
      sourceRefIds: ["nws-fronts", "noaa-weather-map"],
    },
  ],
  precipitationCells: [
    {
      id: "patchy-rain",
      initialCenter: { x: 0.06, y: 0.5 },
      movement: { x: 0.1, y: 0 },
      initialIntensityMmh: 1.8,
      intensityDeltaMmhPerStep: -0.05,
      sourceRefIds: ["nws-fronts"],
    },
  ],
  stationEffects: [
    {
      id: "west-uncertain-change",
      stationId: "west",
      boundaryId: "uncertain-cold-boundary",
      startMinute: 90,
      endMinute: 150,
      delta: {
        temperatureC: -4.5,
        pressureHpa: 2.5,
        pressureTendencyHpaPer3h: 1.5,
        relativeHumidityPct: -10,
        windDirectionDeg: 55,
        windSpeedMps: 2,
        precipitationRateMmh: 2.5,
      },
      noise: {
        temperatureC: { amplitude: 0.5, key: "west-temperature" },
        pressureHpa: { amplitude: 0.4, key: "west-pressure" },
        windDirectionDeg: { amplitude: 8, key: "west-wind" },
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "central-uncertain-change",
      stationId: "central",
      boundaryId: "uncertain-cold-boundary",
      startMinute: 120,
      endMinute: 180,
      delta: {
        temperatureC: -4.5,
        pressureHpa: 2.5,
        pressureTendencyHpaPer3h: 1.5,
        relativeHumidityPct: -10,
        windDirectionDeg: 55,
        windSpeedMps: 2,
        precipitationRateMmh: 2.5,
      },
      noise: {
        temperatureC: { amplitude: 0.5, key: "central-temperature" },
        pressureHpa: { amplitude: 0.4, key: "central-pressure" },
        windDirectionDeg: { amplitude: 8, key: "central-wind" },
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
    {
      id: "east-uncertain-change",
      stationId: "east",
      boundaryId: "uncertain-cold-boundary",
      startMinute: 180,
      endMinute: 240,
      delta: {
        temperatureC: -4.5,
        pressureHpa: 2.5,
        pressureTendencyHpaPer3h: 1.5,
        relativeHumidityPct: -10,
        windDirectionDeg: 55,
        windSpeedMps: 2,
        precipitationRateMmh: 2.5,
      },
      noise: {
        temperatureC: { amplitude: 0.5, key: "east-temperature" },
        pressureHpa: { amplitude: 0.4, key: "east-pressure" },
        windDirectionDeg: { amplitude: 8, key: "east-wind" },
      },
      sourceRefIds: ["nws-fronts", "ngss-ms-ess2-5"],
    },
  ],
  forecastWindows: [
    {
      id: "harbor-next-four-hours",
      targetStationIds: ["central"],
      startMinute: 30,
      endMinute: 210,
    },
  ],
  evidence: [
    {
      id: "uncertain-station-trends",
      type: "trend",
      availableAtMinute: 60,
      targetIds: ["west", "central", "east"],
      learningTags: ["noise", "pressure", "timing"],
    },
    {
      id: "uncertain-boundary-position",
      type: "boundary",
      availableAtMinute: 60,
      targetIds: ["uncertain-cold-boundary"],
      learningTags: ["front-motion", "uncertainty"],
    },
    {
      id: "uncertain-patchy-rain",
      type: "precipitation",
      availableAtMinute: 90,
      targetIds: ["patchy-rain"],
      learningTags: ["precipitation", "uncertainty"],
    },
  ],
  acceptedRanges: [
    {
      id: "uncertain-central-forecast",
      forecastWindowId: "harbor-next-four-hours",
      targetStationId: "central",
      transitionArrivalMinute: { min: 120, max: 210 },
      temperatureChangeC: { min: -6, max: -2 },
      precipitationProbabilityPct: { min: 35, max: 70 },
      windDirectionSectorsDeg: [{ min: 200, max: 250 }],
      defensibleConfidence: ["low", "medium"],
    },
  ],
  debrief: [
    {
      id: "uncertain-calibration-debrief",
      evidenceIds: [
        "uncertain-station-trends",
        "uncertain-boundary-position",
        "uncertain-patchy-rain",
      ],
      outcomeDimensions: ["temperature", "pressure", "wind", "precipitation", "timing", "uncertainty"],
      explanation:
        "The direction of change was supported, but deterministic observational variation and a broader transition made exact timing less certain. Medium or low confidence can therefore be better calibrated than unjustified precision.",
      sourceRefIds: ["ngss-ms-ess2-5", "nws-fronts"],
    },
  ],
  sources: coreSources,
  simplifications: commonSimplifications,
});

export const canonicalFrontPassageScenarios: readonly WeatherScenarioV1[] = [
  guidedColdFront,
  independentColdFront,
  warmFront,
  uncertainBoundary,
];

export {
  guidedColdFront,
  independentColdFront,
  warmFront,
  uncertainBoundary,
};
